### ISSUE TITLE
Compile error after make command

### ISSUE THREAD

**Issue by vikonik** [raspberrypi/debugprobe#106]
Hello. I want to build a project.
I'm doing it step by step as stated in Hacking. When I run the make command I get an error.
![ErrorPicoprobe](https://github.com/raspberrypi/picoprobe/assets/40612015/f7762fdb-49a1-473c-aac7-cd51d6326a12)
How to fix it? Help me please.

**Comment by flfue** [comment]
Maybe too late, but did you also checkout the submodules in the pico-sdk?
