### ISSUE TITLE
Incorrect macro used in ifdef can cause a build failure

### ISSUE THREAD

**Issue by dlly11** [raspberrypi/debugprobe#128]
# Incorrect macro used in ifdef can cause a build failure

Seems to be a typo which would cause a build failure for boards with that have an RX UART LED but not a TX UART LED

## Problem
When compiling with `PICOPROBE_UART_RX_LED` defined but not `PICOPROBE_UART_TX_LED`, the build will fail.

https://github.com/raspberrypi/debugprobe/blob/5ab8c86465c39ecc55c9bc40f21728d692269698/src/cdc_uart.c#L161C1-L163C25

## Solution
Change `#ifdef PICOPROBE_UART_RX_LED` to  `#ifdef PICOPROBE_UART_TX_LED`

**Comment by dlly11** [comment]
Pull request to fix here: https://github.com/raspberrypi/debugprobe/pull/129

**Comment by P33M** [comment]
Applied, thanks.
