### ISSUE TITLE
YD-RP2040 

### ISSUE THREAD

**Issue by mischievous** [raspberrypi/debugprobe#134]
I purchased these from amazon.  So far they are working great.  I tried to connect the Debug Probe to it but it's not working.   Is it the hardware, openocd, debug probe ?  Is it my bad solder job?  How would I go about debugging this?

https://www.amazon.com/RP2040-Board-Type-C-Raspberry-Micropython/dp/B0CG9FWDDC?ref_=v_sp_product_dpx&th=1

**Comment by mischievous** [comment]
This is the error I am getting from openocd. 

** Programming Started **
Error: Unknown flash device (ID 0x0018405e)
Error: auto_probe failed
** Programming Failed **
shutdown command invoked

**Comment by P33M** [comment]
Ask the vendor for support.

**Comment by mischievous** [comment]
It was an openocd issue.
