### ISSUE TITLE
USB Power Descriptor a little on the low side for -DDEBUG_ON_PICO=1?

### ISSUE THREAD

**Issue by peardox** [raspberrypi/debugprobe#148]
In [usb_descriptors.c](https://github.com/raspberrypi/debugprobe/blob/master/src/usb_descriptors.c#L102C3-L102C24) the max power in ma is defined as 100ma via TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_TOTAL_LEN, 0, 100)

While this seems fine for the pre-built probe it does seem a little stingy if -DDEBUG_ON_PICO=1 as if for example you had a pico_w attached directly to a pico and sharing it's power it is quite easy to envisage transient larger power requirements

If a pico is switched to BOOTSEL then the USB descriptor rates it at 500ma - which seems a far more sensible value to use

**Comment by lurch** [comment]
I was wondering if powering 2 Picos from a single USB port is a recommended option, but then I found it explicitly mentioned in the getting-started-guide:
![Screenshot from 2024-08-22 14-37-47](https://github.com/user-attachments/assets/6c06312b-0e42-4b85-9dfc-e05baec419ec)

**Comment by P33M** [comment]
It's explicitly set low because otherwise and if plugged into a bus-powered hub, it will usually get ignored by the host OS. That's more irritating to debug for users.
