### ISSUE TITLE
Can Picoprobe debug STM32 in MDK？

### ISSUE THREAD

**Issue by Hemistic** [raspberrypi/debugprobe#75]
Hello, I have a pico development board and I want to debug STM32 in Keil5, is that possible? I tried a lot, but it doesn't like a typical DAPLink. What setting should I change in the firmware?

**Comment by P33M** [comment]
Have you tried following Keil's instructions? https://developer.arm.com/documentation/101451/0100/Configure-Debugger-Driver

**Comment by kewxke** [comment]
keil mdk5 will not recognize the pi debug probe by default, even if I have assigned the default cmsis-dap.inf in keil mdk directory. So it means keil mdk5 pack cmsis dap driver is not compiled for Pi debug probe.

**Comment by P33M** [comment]
Works for me in MDK 5 with an NXP and STM32 MCU, following Keil's instructions
